export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const INSERT_CUSTOMER = 'INSERT_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const LOGIN_REQUEST = 'LOGIN_REQUEST' ;
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS' ;
export const LOGIN_FAILURE = 'LOGIN_FAILURE';